from google.genai import types
from config import client, MODEL_NAME, GITHUB_TOKEN, GITHUB_DEFAULT_BRANCH
import subprocess
import json
import re
from github import Github, GithubException


active_agents = {}

""" Create agent function"""
def create_agent(agent_name: str, description: str, system_instruction: str):
    print("Creating agent...")
    if client is None:
        raise ValueError("Agent client has not been initialized.")

    if agent_name in active_agents:
        print(f"Warning: Agent '{agent_name}' already exists. Overwriting existing agent.")

    config = types.GenerateContentConfig(
        system_instruction=system_instruction,
        temperature=0.7
    )

    chat = client.chats.create(
        model=MODEL_NAME,
        config=config,
    )
    active_agents[agent_name] = chat
    print(f"Agent '{agent_name}' created successfully.")
    return {
        "message": f"Agent '{agent_name}' created successfully.",
        "active_agents": list(active_agents.keys())
    }

# generate agent plan function
def generate_agent_plan(agent_name: str, instruction_prompt: str):
    if agent_name not in active_agents:
        return {"error": f"Agent '{agent_name}' does not exist."}
    print("Generating plan for agent...")

    print(agent_name)
    chat = active_agents[agent_name]
    response = chat.send_message(instruction_prompt)

    return {
        "message": f"Plan generated by agent '{agent_name}'.",
        "plan": response.text
    }

""" Conflict in implementation plan checking and resolution functions """
def build_conflict_checker_instruction(task_prompt: str, implementation_plans: list[str]) -> str:
    return f"""
    You are a Plan Conflict Checker Agent.

    Your job is to review implementation plans generated by other agents and detect conflicts before execution.

    INPUTS:
    - Original task: {task_prompt}
    - Implementation plans:
    {json.dumps(implementation_plans, indent=2)}

    CHECK FOR:
    1. Overlapping work or duplicate effort
    2. Conflicting file changes or responsibilities
    3. Missing dependencies or bad sequencing
    4. Incompatible interfaces, naming, or contracts
    5. Scope mismatch between sub-tasks
    6. Unclear assumptions or missing prerequisites

    RULES:
    - Do not generate code.
    - Rewrite the plans to resolve conflicts.
    - Focus only on plan-level conflicts.
    - Be specific and practical.
    - If no conflict exists, just reply with 'NO'.
    - If any conflicts exists, follow the format below and provide a structured JSON report.

    RETURN JSON ONLY in this format:
    {{
    "summary": "Short summary of the review",
    "verdict": "pass|needs_revision",
    "conflicts": [
        {{
        "type": "duplication|dependency|ordering|interface|scope|missing_info",
        "message": "What the conflict is",
        "suggestion": "How to resolve it"
        }}
    ]
    }}
    """

def check_agent_plan_conflict(task_prompt: str, implementation_plan: str):
    try:
        agent_name = "conflict_checker"
        agent_description = "An agent that checks for conflicts in a given implementation plan."
        agent_system_instruction = """
        You are a Plan Conflict Checker Agent.

    Your responsibility is to review implementation plans from other agents and identify conflicts.
    You must:
    - analyze the plans for overlap, dependency issues, sequencing problems, and incompatible assumptions
    - return a structured JSON report
    - avoid writing implementation code
    - be concise but specific

    If the plan is clear and conflict-free, return a pass verdict.
        
        """
        if agent_name not in active_agents:
            create_agent(agent_name, agent_description, agent_system_instruction)

        conflict_agent = active_agents[agent_name]
        prompt = build_conflict_checker_instruction(task_prompt, [implementation_plan])
        
        print("Checking for conflicts in the implementation plan...")
    
        response = conflict_agent.send_message(prompt)

        print("Conflict analysis completed.")
        
        return {
            "message": f"Conflict analysis by agent '{agent_name}'.",
            "conflict_analysis": response.text
        }
    except Exception as e:
        print(f"Error during conflict analysis: {e}")
        return {
            "error": f"Error during conflict analysis: {e}"
        }

def parse_conflict_response(response):
    # Accept either the raw dict returned by check_agent_plan_conflict or a raw text string.
    text = ""
    if isinstance(response, dict):
        text = response.get("conflict_analysis", "") or response.get("message", "")
    else:
        text = str(response)

    text_stripped = text.strip()
    if text_stripped.upper() == "NO":
        return {"has_conflict": False, "verdict": "pass", "summary": "No conflicts found", "conflicts": []}

    try:
        payload = json.loads(text_stripped)
        verdict = payload.get("verdict") or ("pass" if not payload.get("conflicts") else "needs_revision")
        has_conflict = verdict != "pass"
        return {
            "has_conflict": has_conflict,
            "verdict": verdict,
            "summary": payload.get("summary", ""),
            "conflicts": payload.get("conflicts", [])
        }
    except Exception:
        return {"has_conflict": True, "verdict": "needs_revision", "summary": text_stripped, "conflicts": []}

def conflict_resolver(task_prompt: str, summary: str, conflicts: list):
    try:
        agent_name = "conflict_resolver"
        agent_description = "Resolves plan-level conflicts and returns a consolidated, conflict-free implementation plan."
        agent_system_instruction = """
        You are a Plan Resolver Agent. Your job is to take an original task description, a short summary of conflicts,
        and a list of conflict objects, and produce a single clear, ordered, conflict-free implementation plan.
        RETURN JSON ONLY in this format:
        {
          "clean_plan": "A clear, step-by-step implementation plan text",
          "changes": [ { "type": "modify|create|remove", "file": "path/to/file", "reason": "why this change resolves conflict" } ],
          "notes": "optional guidance or assumptions"
        }
        Do not include any extra commentary outside the JSON payload.
        """
        if agent_name not in active_agents:
            create_agent(agent_name, agent_description, agent_system_instruction)

        resolver = active_agents[agent_name]
        prompt = f"""
        Original task:
        {task_prompt}

        Conflict summary:
        {summary}

        Conflicts:
        {json.dumps(conflicts, indent=2)}

        Produce a single conflict-free implementation plan and list the file-level changes required (see instruction above).
        """
        response = resolver.send_message(prompt)
        raw = response.text.strip()

        try:
            payload = json.loads(raw)
            return {"success": True, "clean_plan": payload.get("clean_plan", ""), "changes": payload.get("changes", []), "notes": payload.get("notes", ""), "raw": raw}
        except Exception:
            return {"success": False, "error": "resolver returned non-JSON", "raw": raw}
    except Exception as e:
        return {"success": False, "error": str(e)}

# plan implementation function
def implement_plan(agent_name: str, implementation_plan: str):
    print("Implementing plan for agent...")
    if agent_name not in active_agents:
        return {"error": f"Agent '{agent_name}' does not exist."}
    chat = active_agents[agent_name]

    prompt = f"""
    You are an implementation agent.

    You are provided the following implementation plan. Implement this plan.

    Implementation plan:
    {implementation_plan}

    Requirements:
    - Implement the plan by producing the code files described or modified.
    - For each code file you produce or modify, include the filename and the full file contents.
    - Return ONLY valid JSON with a top-level key "files" whose value is an array of objects with keys:
    - "filename": path to the file (string)
    - "content": full file contents (string)
    Example:
    [{"filename": "path/to/file.py", "content": "# file contents..."}]
    - Do not include any extra commentary outside the JSON payload.

    """
    response = chat.send_message(prompt)

    return {
        "message": f"Plan implemented by agent '{agent_name}'.",
        "implementation_result": response.text
    }

# code verification
def verify_agent_code(raw_code: str):
    try:
        # Check if Docker is available
        docker_check = subprocess.run(
            ["docker", "--version"],
            capture_output=True,
            text=True,
            timeout=5
        )
        if docker_check.returncode != 0:
            return {
                "success": False,
                "output": "",
                "error": "Docker is not installed or not running. Code verification requires Docker."
            }

        code_res = subprocess.run(
            ["docker", "run", "--rm", "-i", "--network", "host", "python:3.11-slim", "python"],
            input=raw_code,
            capture_output=True,
            text=True,
            timeout=10
        )
        return {
            "success": code_res.returncode == 0,
            "output": code_res.stdout,
            "error": code_res.stderr
        }
    except subprocess.TimeoutExpired:
        return {
            "success": False,
            "output": "",
            "error": "Verification failed: Code execution timed out (possible infinite loop)."
        }
    except FileNotFoundError:
        return {
            "success": False,
            "output": "",
            "error": "Docker command not found. Please ensure Docker is installed and accessible."
        }
    except Exception as e:
        return {"success": False, "output": "", "error": f"Unexpected error: {e}"}

""" Bug Resolver Agent """
def build_bug_resolver_instruction(code: str, test_results: str) -> str:
    return f"""
    You are a Bug Resolver Agent.

    Your job is to analyze code with bugs and test results showing failures, then return clean, bug-free code.

    INPUTS:
    - Code with bugs:
    {code}

    - Test results showing errors:
    {test_results}

    BUG TYPES TO FIX:
    1. Syntax errors (typos, missing colons, incorrect indentation)
    2. Logical errors (incorrect logic, wrong conditions, off-by-one errors)
    3. Module deprecation errors (using deprecated functions/modules)
    4. Import errors (missing imports, incorrect module names)
    5. Runtime errors (null pointer exceptions, type errors, etc.)
    6. Test failures (assertions failing, unexpected behavior)

    RULES:
    - Analyze the test results to understand what's failing
    - Fix all identified bugs in the code
    - Maintain the original functionality and structure
    - Add necessary imports if missing
    - Update deprecated code to current standards
    - Ensure the code passes the tests
    - Return ONLY the fixed code without any explanation or commentary

    RETURN ONLY the fixed code, no additional text.
    """

def resolve_bug(code: str, test_results: str):
    try:
        agent_name = "bug_resolver"
        agent_description = "Resolves bugs in code based on test results and returns clean, bug-free code."
        agent_system_instruction = """
        You are a Bug Resolver Agent. Your responsibility is to analyze code with bugs and test results,
        identify all issues (syntax, logical, deprecation, import, runtime errors), and return clean,
        bug-free code that passes all tests. Be thorough and fix all issues systematically.
        """
        
        if agent_name not in active_agents:
            create_agent(agent_name, agent_description, agent_system_instruction)

        resolver = active_agents[agent_name]
        prompt = build_bug_resolver_instruction(code, test_results)
        
        print("Resolving bugs in code...")
        response = resolver.send_message(prompt)
        print("Bug resolution completed.")
        
        return {
            "message": f"Bug resolution by agent '{agent_name}'.",
            "fixed_code": response.text,
            "success": True
        }
    except Exception as e:
        print(f"Error during bug resolution: {e}")
        return {
            "error": f"Error during bug resolution: {e}",
            "success": False
        }

""" Test Generation Agent """
def build_test_generation_instruction(code: str, language: str = "python") -> str:
    return f"""
    You are a Test Generation Agent.

    Your job is to generate comprehensive tests for the provided code.

    INPUTS:
    - Code to test:
    {code}

    - Language: {language}

    REQUIREMENTS:
    1. Generate unit tests that cover all functions and edge cases
    2. Include both positive and negative test cases
    3. Test error handling and boundary conditions
    4. Use appropriate testing framework for the language (pytest for Python)
    5. Make tests self-contained and runnable
    6. Include necessary imports and setup code

    RULES:
    - Generate only test code, no explanations
    - Ensure tests are comprehensive and realistic
    - Use descriptive test names
    - Include assertions that verify expected behavior
    - Return ONLY the test code without any commentary

    RETURN ONLY the test code, no additional text.
    """

def generate_tests(code: str, language: str = "python"):
    try:
        agent_name = "test_generator"
        agent_description = "Generates comprehensive tests for code in various languages."
        agent_system_instruction = """
        You are a Test Generation Agent. Your responsibility is to analyze code and generate
        comprehensive, runnable tests that cover all functionality, edge cases, and error conditions.
        Use appropriate testing frameworks for each language.
        """
        
        if agent_name not in active_agents:
            create_agent(agent_name, agent_description, agent_system_instruction)

        generator = active_agents[agent_name]
        prompt = build_test_generation_instruction(code, language)
        
        print(f"Generating {language} tests...")
        response = generator.send_message(prompt)
        print("Test generation completed.")
        
        return {
            "message": f"Test generation by agent '{agent_name}'.",
            "test_code": response.text,
            "language": language,
            "success": True
        }
    except Exception as e:
        print(f"Error during test generation: {e}")
        return {
            "error": f"Error during test generation: {e}",
            "success": False
        }

""" Python Validation Agent with Docker """
def validate_python_code(code: str, test_code: str = None):
    try:
        # Check if Docker is available
        docker_check = subprocess.run(
            ["docker", "--version"],
            capture_output=True,
            text=True,
            timeout=5
        )
        if docker_check.returncode != 0:
            return {
                "success": False,
                "output": "",
                "error": "Docker is not installed or not running. Code validation requires Docker."
            }

        # Prepare the code to run
        code_to_run = code
        if test_code:
            code_to_run = f"{code}\n\n{test_code}"

        # Run Python code in isolated Docker container
        docker_command = [
            "docker", "run", "--rm",
            "-i",  # Read from stdin
            "--network", "none",  # Network isolation
            "--memory", "512m",  # Memory limit
            "--cpus", "1.0",  # CPU limit
            "-w", "/workspace",  # Working directory
            "python:3.11-slim",
            "python", "-c", code_to_run
        ]

        result = subprocess.run(
            docker_command,
            capture_output=True,
            text=True,
            timeout=30
        )

        return {
            "success": result.returncode == 0,
            "output": result.stdout,
            "error": result.stderr,
            "exit_code": result.returncode
        }
    except subprocess.TimeoutExpired:
        return {
            "success": False,
            "output": "",
            "error": "Validation failed: Code execution timed out (possible infinite loop).",
            "exit_code": -1
        }
    except FileNotFoundError:
        return {
            "success": False,
            "output": "",
            "error": "Docker command not found. Please ensure Docker is installed and accessible.",
            "exit_code": -1
        }
    except Exception as e:
        return {
            "success": False,
            "output": "",
            "error": f"Unexpected error during validation: {e}",
            "exit_code": -1
        }

""" Validation Workflow with Auto-Fix Loop """
def validate_code_with_autofix(code: str, language: str = "python", max_attempts: int = 2):
    
    print(f"Starting validation workflow for {language} code...")
    
    current_code = code
    attempt = 0
    
    while attempt <= max_attempts:
        attempt += 1
        print(f"Validation attempt {attempt}/{max_attempts + 1}")
        
        test_result = generate_tests(current_code, language)
        if not test_result.get("success"):
            print("Failed to generate tests, proceeding with basic validation")
            test_code = None
        else:
            test_code = test_result.get("test_code")
        
        if language == "python":
            validation_result = validate_python_code(current_code, test_code)
        else:
            # For other languages, basic validation (can be extended)
            validation_result = validate_python_code(current_code, test_code)
        
        # Step 3: Check if validation passed
        if validation_result.get("success"):
            print("Code validation passed!")
            return {
                "success": True,
                "validated_code": current_code,
                "test_results": validation_result.get("output"),
                "attempts": attempt,
                "message": "Code validated successfully"
            }
        
        # Step 4: If validation failed and we have attempts left, try to fix
        if attempt <= max_attempts:
            print(f"Validation failed: {validation_result.get('error')}")
            print("Attempting to fix bugs...")
            
            # Combine code and test results for bug resolver
            test_results = validation_result.get("error")
            if test_code:
                test_results = f"Test Code:\n{test_code}\n\nError Output:\n{validation_result.get('error')}"
            
            # Use bug resolver to fix the code
            fix_result = resolve_bug(current_code, test_results)
            
            if fix_result.get("success"):
                current_code = fix_result.get("fixed_code")
                print("Bug fix applied, re-validating...")
            else:
                print(f"Bug fix failed: {fix_result.get('error')}")
                break
        else:
            print("Max attempts reached, validation failed")
    
    # If we get here, validation failed after all attempts
    return {
        "success": False,
        "original_code": code,
        "last_attempt_code": current_code,
        "error": validation_result.get("error"),
        "attempts": attempt,
        "message": f"Validation failed after {attempt} attempts"
    }

""" GitHub Agent Functions """
def parse_github_repo_url(repo_url: str):
    """Parse GitHub repository URL to extract owner and repo name"""
    # Handle various GitHub URL formats
    patterns = [
        r'github\.com/([^/]+)/([^/]+?)(\.git)?$',  # https://github.com/owner/repo or https://github.com/owner/repo.git
        r'github\.com/([^/]+)/([^/]+)',             # github.com/owner/repo
    ]
    
    for pattern in patterns:
        match = re.search(pattern, repo_url)
        if match:
            owner = match.group(1)
            repo_name = match.group(2).replace('.git', '')
            return owner, repo_name
    
    raise ValueError(f"Invalid GitHub repository URL: {repo_url}")

def create_github_branch(repo_url: str, branch_name: str, base_branch: str = None, github_token: str = None):
    """Create a new branch in a GitHub repository"""
    try:
        # Use provided token or fall back to config
        token = github_token or GITHUB_TOKEN
        if not token:
            return {
                "success": False,
                "branch_name": branch_name,
                "error": "GitHub token not provided. Please set GITHUB_TOKEN in config or provide it in the request.",
                "message": "Authentication failed"
            }
        
        # Parse repository URL
        owner, repo_name = parse_github_repo_url(repo_url)
        
        # Initialize GitHub client
        g = Github(token)
        repo = g.get_repo(f"{owner}/{repo_name}")
        
        # Get base branch (default to main or configured default)
        base_branch_name = base_branch or GITHUB_DEFAULT_BRANCH or 'main'
        
        # Get the base branch
        try:
            base_branch = repo.get_branch(base_branch_name)
        except GithubException as e:
            return {
                "success": False,
                "branch_name": branch_name,
                "error": f"Base branch '{base_branch_name}' not found: {str(e)}",
                "message": "Base branch not found"
            }
        
        # Create new branch
        repo.create_git_ref(
            ref=f"refs/heads/{branch_name}",
            sha=base_branch.commit.sha
        )
        
        branch_url = f"https://github.com/{owner}/{repo_name}/tree/{branch_name}"
        
        print(f"Successfully created branch '{branch_name}' in {owner}/{repo_name}")
        
        return {
            "success": True,
            "branch_name": branch_name,
            "branch_url": branch_url,
            "message": f"Branch '{branch_name}' created successfully"
        }
        
    except ValueError as e:
        return {
            "success": False,
            "branch_name": branch_name,
            "error": str(e),
            "message": "Invalid repository URL"
        }
    except GithubException as e:
        return {
            "success": False,
            "branch_name": branch_name,
            "error": f"GitHub API error: {str(e)}",
            "message": "GitHub operation failed"
        }
    except Exception as e:
        return {
            "success": False,
            "branch_name": branch_name,
            "error": f"Unexpected error: {str(e)}",
            "message": "Operation failed"
        }

def commit_and_push_to_github(repo_url: str, branch_name: str, files: dict, commit_message: str, github_token: str = None):
    """Commit and push files to a GitHub repository branch"""
    try:
        # Use provided token or fall back to config
        token = github_token or GITHUB_TOKEN
        if not token:
            return {
                "success": False,
                "branch_name": branch_name,
                "error": "GitHub token not provided. Please set GITHUB_TOKEN in config or provide it in the request.",
                "message": "Authentication failed"
            }
        
        # Parse repository URL
        owner, repo_name = parse_github_repo_url(repo_url)
        
        # Initialize GitHub client
        g = Github(token)
        repo = g.get_repo(f"{owner}/{repo_name}")
        
        # Get the branch
        try:
            branch = repo.get_branch(branch_name)
        except GithubException as e:
            return {
                "success": False,
                "branch_name": branch_name,
                "error": f"Branch '{branch_name}' not found: {str(e)}",
                "message": "Branch not found"
            }
        
        # Create or update files
        files_committed = []
        for file_path, file_content in files.items():
            try:
                # Try to get the file to see if it exists
                try:
                    file = repo.get_contents(file_path, ref=branch_name)
                    # Update existing file
                    repo.update_file(
                        path=file_path,
                        message=commit_message,
                        content=file_content,
                        sha=file.sha,
                        branch=branch_name
                    )
                except GithubException:
                    # File doesn't exist, create it
                    repo.create_file(
                        path=file_path,
                        message=commit_message,
                        content=file_content,
                        branch=branch_name
                    )
                
                files_committed.append(file_path)
                print(f"Successfully committed {file_path}")
                
            except Exception as e:
                print(f"Failed to commit {file_path}: {str(e)}")
                continue
        
        if not files_committed:
            return {
                "success": False,
                "branch_name": branch_name,
                "error": "No files were committed",
                "message": "Commit operation failed"
            }
        
        # Get the latest commit SHA
        branch = repo.get_branch(branch_name)
        commit_sha = branch.commit.sha
        branch_url = f"https://github.com/{owner}/{repo_name}/tree/{branch_name}"
        
        print(f"Successfully committed {len(files_committed)} files to branch '{branch_name}'")
        
        return {
            "success": True,
            "commit_sha": commit_sha,
            "branch_url": branch_url,
            "files_committed": files_committed,
            "message": f"Successfully committed {len(files_committed)} files"
        }
        
    except ValueError as e:
        return {
            "success": False,
            "branch_name": branch_name,
            "error": str(e),
            "message": "Invalid repository URL"
        }
    except GithubException as e:
        return {
            "success": False,
            "branch_name": branch_name,
            "error": f"GitHub API error: {str(e)}",
            "message": "GitHub operation failed"
        }
    except Exception as e:
        return {
            "success": False,
            "branch_name": branch_name,
            "error": f"Unexpected error: {str(e)}",
            "message": "Operation failed"
        }