from google.genai import types, Client

active_agents = {}

client = None

def set_client(api_client):
    global client
    client = api_client

def create_agent(agent_name: str, description: str, system_instruction: str):
    print("Creating agent...")
    if client is None:
        raise ValueError("Agent client has not been initialized.")

    config = types.GenerateContentConfig(
        system_instruction=system_instruction,
        temperature=0.7
    )
    
    chat = client.chats.create(
        model='gemini-3.5-flash',
        config=config,
    )
    active_agents[agent_name] = chat
    print(f"Agent '{agent_name}' created successfully.")
    return {
        "message": f"Agent '{agent_name}' created successfully.",
        "active_agents": list(active_agents.keys())
    }

def generate_agent_plan(agent_name: str, instruction_prompt: str):
    if agent_name not in active_agents:
        return {"error": f"Agent '{agent_name}' does not exist."}
    print("Generating plan for agent...")
    
    print(agent_name)
    chat = active_agents[agent_name]
    response = chat.send_message(instruction_prompt)
    print(f"Plan generated by agent '{agent_name}': {response.text}")

    return {
        "message": f"Plan generated by agent '{agent_name}'.",
        "plan": response.text
    }

import json

def build_conflict_checker_instruction(task_prompt: str, implementation_plans: list[str]) -> str:
    return f"""
You are a Plan Conflict Checker Agent.

Your job is to review implementation plans generated by other agents and detect conflicts before execution.

INPUTS:
- Original task: {task_prompt}
- Implementation plans:
{json.dumps(implementation_plans, indent=2)}

CHECK FOR:
1. Overlapping work or duplicate effort
2. Conflicting file changes or responsibilities
3. Missing dependencies or bad sequencing
4. Incompatible interfaces, naming, or contracts
5. Scope mismatch between sub-tasks
6. Unclear assumptions or missing prerequisites

RULES:
- Do not generate code.
- Rewrite the plans to resolve conflicts.
- Focus only on plan-level conflicts.
- Be specific and practical.
- If no conflict exists, say so clearly.

RETURN JSON ONLY in this format:
{{
  "summary": "Short summary of the review",
  "verdict": "pass|needs_revision",
  "conflicts": [
    {{
      "severity": "low|medium|high",
      "type": "duplication|dependency|ordering|interface|scope|missing_info",
      "message": "What the conflict is",
      "suggestion": "How to resolve it"
    }}
  ]
}}
"""

def check_agent_plan_conflict(task_prompt: str, implementation_plan: str):
    try:
        agent_name = "conflict_checker"
        agent_description = "An agent that checks for conflicts in a given implementation plan."
        agent_system_instruction = """
        You are a Plan Conflict Checker Agent.

Your responsibility is to review implementation plans from other agents and identify conflicts.
You must:
- analyze the plans for overlap, dependency issues, sequencing problems, and incompatible assumptions
- return a structured JSON report
- avoid writing implementation code
- be concise but specific

If the plan is clear and conflict-free, return a pass verdict.
        
        """
        if agent_name not in active_agents:
            create_agent(agent_name, agent_description, agent_system_instruction)

        conflict_agent = active_agents[agent_name]
        prompt = build_conflict_checker_instruction(task_prompt, [implementation_plan])
        
        print("Checking for conflicts in the implementation plan...")
    
        response = conflict_agent.send_message(prompt)

        print("Conflict analysis completed.")
        
        return {
            "message": f"Conflict analysis by agent '{agent_name}'.",
            "conflict_analysis": response.text
        }
    except Exception as e:
        print(f"Error during conflict analysis: {e}")
        return {
            "error": f"Error during conflict analysis: {e}"
        }