from google.genai import types
from config import client, MODEL_NAME
import subprocess
import json


active_agents = {}

""" Create agent function"""
def create_agent(agent_name: str, description: str, system_instruction: str):
    print("Creating agent...")
    if client is None:
        raise ValueError("Agent client has not been initialized.")

    if agent_name in active_agents:
        print(f"Warning: Agent '{agent_name}' already exists. Overwriting existing agent.")

    config = types.GenerateContentConfig(
        system_instruction=system_instruction,
        temperature=0.7
    )

    chat = client.chats.create(
        model=MODEL_NAME,
        config=config,
    )
    active_agents[agent_name] = chat
    print(f"Agent '{agent_name}' created successfully.")
    return {
        "message": f"Agent '{agent_name}' created successfully.",
        "active_agents": list(active_agents.keys())
    }

# generate agent plan function
def generate_agent_plan(agent_name: str, instruction_prompt: str):
    if agent_name not in active_agents:
        return {"error": f"Agent '{agent_name}' does not exist."}
    print("Generating plan for agent...")

    print(agent_name)
    chat = active_agents[agent_name]
    response = chat.send_message(instruction_prompt)

    return {
        "message": f"Plan generated by agent '{agent_name}'.",
        "plan": response.text
    }

""" Conflict in implementation plan checking and resolution functions """
def build_conflict_checker_instruction(task_prompt: str, implementation_plans: list[str]) -> str:
    return f"""
    You are a Plan Conflict Checker Agent.

    Your job is to review implementation plans generated by other agents and detect conflicts before execution.

    INPUTS:
    - Original task: {task_prompt}
    - Implementation plans:
    {json.dumps(implementation_plans, indent=2)}

    CHECK FOR:
    1. Overlapping work or duplicate effort
    2. Conflicting file changes or responsibilities
    3. Missing dependencies or bad sequencing
    4. Incompatible interfaces, naming, or contracts
    5. Scope mismatch between sub-tasks
    6. Unclear assumptions or missing prerequisites

    RULES:
    - Do not generate code.
    - Rewrite the plans to resolve conflicts.
    - Focus only on plan-level conflicts.
    - Be specific and practical.
    - If no conflict exists, just reply with 'NO'.
    - If any conflicts exists, follow the format below and provide a structured JSON report.

    RETURN JSON ONLY in this format:
    {{
    "summary": "Short summary of the review",
    "verdict": "pass|needs_revision",
    "conflicts": [
        {{
        "type": "duplication|dependency|ordering|interface|scope|missing_info",
        "message": "What the conflict is",
        "suggestion": "How to resolve it"
        }}
    ]
    }}
    """

def check_agent_plan_conflict(task_prompt: str, implementation_plan: str):
    try:
        agent_name = "conflict_checker"
        agent_description = "An agent that checks for conflicts in a given implementation plan."
        agent_system_instruction = """
        You are a Plan Conflict Checker Agent.

    Your responsibility is to review implementation plans from other agents and identify conflicts.
    You must:
    - analyze the plans for overlap, dependency issues, sequencing problems, and incompatible assumptions
    - return a structured JSON report
    - avoid writing implementation code
    - be concise but specific

    If the plan is clear and conflict-free, return a pass verdict.
        
        """
        if agent_name not in active_agents:
            create_agent(agent_name, agent_description, agent_system_instruction)

        conflict_agent = active_agents[agent_name]
        prompt = build_conflict_checker_instruction(task_prompt, [implementation_plan])
        
        print("Checking for conflicts in the implementation plan...")
    
        response = conflict_agent.send_message(prompt)

        print("Conflict analysis completed.")
        
        return {
            "message": f"Conflict analysis by agent '{agent_name}'.",
            "conflict_analysis": response.text
        }
    except Exception as e:
        print(f"Error during conflict analysis: {e}")
        return {
            "error": f"Error during conflict analysis: {e}"
        }

def parse_conflict_response(response):
    # Accept either the raw dict returned by check_agent_plan_conflict or a raw text string.
    text = ""
    if isinstance(response, dict):
        text = response.get("conflict_analysis", "") or response.get("message", "")
    else:
        text = str(response)

    text_stripped = text.strip()
    if text_stripped.upper() == "NO":
        return {"has_conflict": False, "verdict": "pass", "summary": "No conflicts found", "conflicts": []}

    try:
        payload = json.loads(text_stripped)
        verdict = payload.get("verdict") or ("pass" if not payload.get("conflicts") else "needs_revision")
        has_conflict = verdict != "pass"
        return {
            "has_conflict": has_conflict,
            "verdict": verdict,
            "summary": payload.get("summary", ""),
            "conflicts": payload.get("conflicts", [])
        }
    except Exception:
        return {"has_conflict": True, "verdict": "needs_revision", "summary": text_stripped, "conflicts": []}

def conflict_resolver(task_prompt: str, summary: str, conflicts: list):
    try:
        agent_name = "conflict_resolver"
        agent_description = "Resolves plan-level conflicts and returns a consolidated, conflict-free implementation plan."
        agent_system_instruction = """
        You are a Plan Resolver Agent. Your job is to take an original task description, a short summary of conflicts,
        and a list of conflict objects, and produce a single clear, ordered, conflict-free implementation plan.
        RETURN JSON ONLY in this format:
        {
          "clean_plan": "A clear, step-by-step implementation plan text",
          "changes": [ { "type": "modify|create|remove", "file": "path/to/file", "reason": "why this change resolves conflict" } ],
          "notes": "optional guidance or assumptions"
        }
        Do not include any extra commentary outside the JSON payload.
        """
        if agent_name not in active_agents:
            create_agent(agent_name, agent_description, agent_system_instruction)

        resolver = active_agents[agent_name]
        prompt = f"""
        Original task:
        {task_prompt}

        Conflict summary:
        {summary}

        Conflicts:
        {json.dumps(conflicts, indent=2)}

        Produce a single conflict-free implementation plan and list the file-level changes required (see instruction above).
        """
        response = resolver.send_message(prompt)
        raw = response.text.strip()

        try:
            payload = json.loads(raw)
            return {"success": True, "clean_plan": payload.get("clean_plan", ""), "changes": payload.get("changes", []), "notes": payload.get("notes", ""), "raw": raw}
        except Exception:
            return {"success": False, "error": "resolver returned non-JSON", "raw": raw}
    except Exception as e:
        return {"success": False, "error": str(e)}

# plan implementation function
def implement_plan(agent_name: str, implementation_plan: str):
    print("Implementing plan for agent...")
    if agent_name not in active_agents:
        return {"error": f"Agent '{agent_name}' does not exist."}
    chat = active_agents[agent_name]

    prompt = f"""
    You are an implementation agent.

    You are provided the following implementation plan. Implement this plan.

    Implementation plan:
    {implementation_plan}

    Requirements:
    - Implement the plan by producing the code files described or modified.
    - For each code file you produce or modify, include the filename and the full file contents.
    - Return ONLY valid JSON with a top-level key "files" whose value is an array of objects with keys:
    - "filename": path to the file (string)
    - "content": full file contents (string)
    Example:
    [{"filename": "path/to/file.py", "content": "# file contents..."}]
    - Do not include any extra commentary outside the JSON payload.

    """
    response = chat.send_message(prompt)

    return {
        "message": f"Plan implemented by agent '{agent_name}'.",
        "implementation_result": response.text
    }

# code verification
def verify_agent_code(raw_code: str):
    try:
        # Check if Docker is available
        docker_check = subprocess.run(
            ["docker", "--version"],
            capture_output=True,
            text=True,
            timeout=5
        )
        if docker_check.returncode != 0:
            return {
                "success": False,
                "output": "",
                "error": "Docker is not installed or not running. Code verification requires Docker."
            }

        code_res = subprocess.run(
            ["docker", "run", "--rm", "-i", "--network", "host", "python:3.11-slim", "python"],
            input=raw_code,
            capture_output=True,
            text=True,
            timeout=10
        )
        return {
            "success": code_res.returncode == 0,
            "output": code_res.stdout,
            "error": code_res.stderr
        }
    except subprocess.TimeoutExpired:
        return {
            "success": False,
            "output": "",
            "error": "Verification failed: Code execution timed out (possible infinite loop)."
        }
    except FileNotFoundError:
        return {
            "success": False,
            "output": "",
            "error": "Docker command not found. Please ensure Docker is installed and accessible."
        }
    except Exception as e:
        return {"success": False, "output": "", "error": f"Unexpected error: {e}"}